# Miyoo A30 / my282
OPT = -O3 -fomit-frame-pointer
ARCH = -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard
CFLAGS = $(ARCH) -flto
SDL = SDL2
GL = GLES

CFLAGS += -I$(PREFIX_LOCAL)/include -I$(PREFIX)/include
LDFLAGS = -L$(PREFIX_LOCAL)/lib -L$(PREFIX)/lib
CFLAGS += $$(pkg-config --cflags sdl2)
LDFLAGS += $$(pkg-config --libs sdl2) -lGLESv2 -lEGL
CFLAGS += -DUSE_$(SDL) -DUSE_$(GL) -DGL_GLEXT_PROTOTYPES
LDFLAGS += -l$(SDL)_image -l$(SDL)_ttf -lsamplerate
LDFLAGS += -lasound -lpthread -ldl -lrt -lm -lz
